### ISSUE TITLE
usb devise not reconised?

### ISSUE THREAD

**Issue by dunk8888** [micronucleus/micronucleus#100]
Hi is it normal for the bootloader to leave usb device not recocnised/malfunctioned when the bootloader quits and switches to user code? 1.11 micronucleus doesnt do that,this version does,it works fine but its annoying leaving a usb has malfunctioned bubble in the system tray after bootloader quits.i now use the olde 1.11 version to avoid this.thanks

**Comment by cpldcpu** [comment]
If your userprogram does not use USB, it could pull down the USB lines. This will disconnect USB.
