### ISSUE TITLE
Device does not work at 3V

### ISSUE THREAD

**Issue by tonyputi** [micronucleus/micronucleus#103]
Unable to boot any ATTiny85 with BOD disable powering by a 3V battery.
All work ok with version 1.11 of micronucleus

**Comment by cpldcpu** [comment]
Are your running the device from the battery while using USB? The ATtiny85 needs 5V with a 16 MHz main clock. Anything else may be marginal.

**Comment by Phoenix1747** [comment]
Try decreasing the clock speed and try again.

**Comment by cpldcpu** [comment]
Well, micronucleus requires 16 MHz, so that may not be easy.

**Comment by Phoenix1747** [comment]
Oh, I didn't know that :/
