### ISSUE TITLE
Would you tag v2.03?

### ISSUE THREAD

**Issue by takesako** [micronucleus/micronucleus#120]
Hi, I made the micronucleus install package for Alpine Linux.
https://github.com/takesako/alpine-iot/blob/master/micronucleus/APKBUILD

When building, I want to download the tar archive from github with tag.
The old version was able to download with the following URL:
https://github.com/micronucleus/micronucleus/archive/v2.01.tar.gz

Would you tag v2.03? If you tag v2.03, we can download as flowing URL:
https://github.com/micronucleus/micronucleus/archive/v2.03.tar.gz

Thanks, 
takesako

**Comment by cpldcpu** [comment]
Done! Sorry for the long delay.

The "/archive" feature is really neat. Did not know about it.
