### ISSUE TITLE
released and tagged v2.04

### ISSUE THREAD

**Issue by cpldcpu** [micronucleus/micronucleus#142]
@AHorneffer FYI - I tagged and released v2.04. It seems I forgot to complete this in December. All version numbers are in there and everything is rebuild. Seems the latest AVR-GCC removed around 10 bytes of each version - hopefully not creating new issues.

All new changes should go towards v2.05

**Comment by AHorneffer** [comment]
> All new changes should go towards v2.05

O.K.

**Comment by cpldcpu** [comment]
I created a testing branch for 2.05. 

https://github.com/micronucleus/micronucleus/tree/testing-2.05
