### ISSUE TITLE
Duplicate "releases" directories?

### ISSUE THREAD

**Issue by E3V3A** [micronucleus/micronucleus#147]
There are two different locations of "releases" HEX files. This is somewhat confusing. 
What is the difference, and if there is none, why not using the same directory?

* https://github.com/micronucleus/micronucleus/tree/master/firmware/releases
* https://github.com/micronucleus/micronucleus/tree/master/upgrade/releases

**Comment by cpldcpu** [comment]
Upgrade functionality is described here:

https://github.com/micronucleus/micronucleus/tree/master/upgrade
