### ISSUE TITLE
t_85 default - application in Stand-Alone did not start

### ISSUE THREAD

**Issue by jojo70** [micronucleus/micronucleus#154]
I´m using an Attiny85 which is programmed over USB / micronucleus 2.04
I´m using the Tiny in an stand-alone circuit with analog sensors on A3 / A2 if the analog values are low (ca. 0,5V) the Micronuleus ist running instead of the loaded application.
The Version 1.1 is working fine.

**Comment by ArminJo** [comment]
Try this [release](https://github.com/ArminJo/micronucleus-firmware/blob/master/firmware/releases/t85_entry_on_power_on_no_pullup.hex) or [upgrade](https://github.com/ArminJo/micronucleus-firmware/blob/master/firmware/upgrades/upgrade-t85_entry_on_power_on_no_pullup.hex) version.
I had a similar problem which was solved by this version.
