### ISSUE TITLE
brick programam / Joystick

### ISSUE THREAD

**Issue by RAWeigel** [micronucleus/micronucleus#157]
Sorry, but my english is poor. I use google translate.
In Release 2.03 and 2.04, at some point (USB plug or unplug) I lose access to the program, written to the Digispark card. After reprogramming with the Arduino IDE, it works again.
My program is a 4 button USB HID Joystick.
Does anyone know if this problem is known?

**Comment by ArminJo** [comment]
Seems nobody else knows this.
