### ISSUE TITLE
Question: compiler version/configuration you use?

### ISSUE THREAD

**Issue by bryanjhv** [micronucleus/micronucleus#160]
Hi! I've been trying to compile `t85_default` firmware on a Manjaro system.
I always get a bigger firmware (**~14 bytes** bigger) in contrast to the ones in `firmware/releases` folder.

So, my question is: **are you using an specific avr-gcc version/configuration?**

**Steps I followed:**

```bash
git clone https://github.com/micronucleus/micronucleus.git
cd micronucleus/firmware

git checkout 2.04
make clean
make CONFIG=t85_default
avr-size main.hex releases/t85_default.hex
    # 1602      main.hex
    # 1588      releases/t85_default.hex
```

**Installed packages:**

```txt
avr-binutils   2.32
avr-gcc       9.1.0
avr-libc      2.0.0
make          4.2.1
```

**EDIT:** Please look at https://github.com/micronucleus/micronucleus/issues/160#issuecomment-525649697, this comment was initially referring to `.hex` file sizes which is different and bigger than compiled firmware, now it refers to the compiled size.

**Comment by cpldcpu** [comment]
I usually compile with the toolchain supplied with atmel studio.

avr-gcc (AVR_8_bit_GNU_Toolchain_3.6.1_1750) 5.4.0

Its a bit surprising to see such a huge version gap?

**Comment by cpldcpu** [comment]
Are you actually looking at the file sizes of the hex files? These are of
course larger than the actual binary that is encoded in them. Its a text
based format.
