### ISSUE TITLE
Possible Typo in Readme.txt

### ISSUE THREAD

**Issue by AdnanSlef** [micronucleus/micronucleus#166]
Readme.txt includes the following:

t84_default     -   ATtiny84A default configuration     -   1534 bytes
t841_default    -   ATtiny841 default configuration     -   1586 bytes
t45_default     -   ATtiny85  default configuration     -   1588 bytes
t85_default     -   ATtiny85  default configuration     -   1588 bytes
t85_aggressive  -   ATtiny85  smaller size - critical   -   1418 bytes
t167_default    -   ATtiny167 default (uses xtal)       -   1412 bytes
Nanite841       -   Nanite841 firmware                  -   1610 bytes
m328p_extclock  -   ATMega328p external clock           -   1434 bytes

The line **t45_default     -   ATtiny85  default configuration     -   1588 bytes** appears to contain a typo and should instead read **t45_default     -   ATtiny45  default configuration     -   1588 bytes**

**Comment by cpldcpu** [comment]
Indeed. That was fixed a while ago.
