### ISSUE TITLE
v2.5 build error

### ISSUE THREAD

**Issue by nerdralph** [micronucleus/micronucleus#183]
I checked out v2.5:
```git clone -b version_2.5 https://github.com/micronucleus/micronucleus.git```
Then I tried to build t85_default:
```
$ make CONFIG=t85_default
Building Micronucleus configuration: t85_default
Size of binary hexfile. Use the data size to calculate the bootloader address:
   text    data     bss     dec     hex filename
      0    1542       0    1542     606 main.hex
extern const uint8_t bootloader [] PROGMEM
extern const uint8_t bootloader_end [] PROGMEM
extern const uint8_t bootloader_size_sym []


upgrade.c: In function 'write_new_bootloader':
upgrade.c:94:23: error: 'bootloader_size' undeclared (first use in this function)
   while ( page_addr < bootloader_size ) {
                       ^
```
I tried on Debian 10 and MinGW, and get the same error in both cases.

**Comment by nerdralph** [comment]
I'm finding that your micronucleus-firmware repo isn't stable.  I'm getting "flash write error -1 " with t85_aggressive, while 2.04 works error-free.

**Comment by ArminJo** [comment]
I am sorry, but I just tested t85_agressive with my Digispark and it had again no error (I never saw one with the aggressive version). Maybe your internal oscillator frequency is slightly deviated. In this case errors may happen sometimes, also depending on temperature.
In 2.5, there are only pushes replaced by pops, but this does not change the timing and cannot trigger this error.

**Comment by nerdralph** [comment]
I'm not getting any errors now on t85_aggressive with my fork that fixes the register assignments.  I suspect the issue is related to the register allocation bug.
https://github.com/ArminJo/micronucleus-firmware/issues/11
It's just a lucky fluke that your builds haven't failed.  I disassembled a couple of my builds and noticed r17 and Y were being used, so clobbering them in USB_handler could cause unpredictable failures.  Different compiler versions and different optimizations in the build will impact how avr-gcc uses registers.

mn 2.04 saves all the registers in USB_handler, so there is no chance of it corrupting registers that are used by main.

**Comment by cpldcpu** [comment]
I am closing this, as it does not refer to this repository.
