### ISSUE TITLE
Please enable discussions

### ISSUE THREAD

**Issue by ArminJo** [micronucleus/micronucleus#199]
See: https://docs.github.com/en/github/administering-a-repository/enabling-or-disabling-github-discussions-for-a-repository#enabling-or-disabling-discussions-for-your-repository

**Comment by cpldcpu** [comment]
Done! Excellent idea. The welcome message may need some editing.

Btw, maybe we could use the Wiki to store supporting information? Setting up Jekyll somehow got stuck on my side. 
The wiki works quite well too. Or maybe even discussions are sufficient.
