### ISSUE TITLE
[BUG] Unable to read from stdin

### ISSUE THREAD

**Issue by twisty-doerofthings** [micronucleus/micronucleus#214]
Please also have a look at discussion:  #171 

**Describe the bug**
When attempting to use "-" as the Filename, an error is generated. From Help:

`Path to intel hex or raw data file to upload, or "-" to read from stdin`

Response:

`Unrecognized option: -`

**To Reproduce**
1. Download 5.2pre (micronucleus-master-LATEST.zip), extract, and change to this directory
2. Change to Commandline directory `cd commandline`
3. Make `sudo make CONFIG=t84_config`
4. Install `sudo make install`
5. Change to parent `cd ..`
6. Test `micronucleus -`
7. See error

**Expected behavior**
Running command should result in reading from stdin:

    Please plug in the device ... 
    Press CTRL+C to terminate the program.

**Used Hardware**
Attiny84
https://learn.sparkfun.com/tutorials/roshamglo-hookup-guide

**Desktop:**
 - OS: Linux 5.4.0-65-generic #73-Ubuntu SMP x86_64 GNU/Linux
 - Development environment: Arduino / CMD
 - Version of the bootloader: micronucleus-cli version: 2.5

**Comment by ArminJo** [comment]
Thanks for reporting 👍
