### ISSUE TITLE
ATtiny4313 Compatibility

### ISSUE THREAD

**Issue by RobertDaleSmith** [micronucleus/micronucleus#237]
I am looking at implementing micronucleus onto a ATtiny4313. I believe it is close enough to ATtiny85 to work. Can some one confirm this is possible to use with ATtiny4313?

**Comment by RobertDaleSmith** [comment]
I was able to get this to compiled and flashed but the USB device is not being properly recognized by Windows or MacOS. My schematic is missing the 3.6 zeners so maybe that is what is going on. The LED on my device does have a blinking pattern after flashing the micronucleus bootloader. Not sure what I'm doing wrong here.

**Comment by RobertDaleSmith** [comment]
I was able to put together a working ATtiny4313 firmware configuration for my project. I have opened a PR against testing. (#238)

**Comment by cpldcpu** [comment]
Thanks!
