### ISSUE TITLE
[BUG] Attiny85 USB bootloader device not recognized with 2.5

### ISSUE THREAD

**Issue by ranger81** [micronucleus/micronucleus#248]
My Digistump Digispark board is no longer recognized by my computer when using the t85_default.hex of release version **2.5**.
If I upload the previous t85_default.hex of release version **2.04** to the same hardware, it works perfectly.
As far as I noticed, the configuration was not updated between the releases or is there something to mind of when updating to the 2.5 release?

The micronucleus program version 2.5 therefore is also unable to detect the device and sits at
`> Please plug in the device...`

**To Reproduce**
1. Flash t85_default.hex of release 2.5, plug USB in, unknown device
2. Flash t85_default.hex of release 2.04, plug USB in, device recognized

**Used Hardware**
Digispark Digistump board.

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Development environment: Arduino IDE, AVRdude
 - Version of the bootloader: 2.5 and 2.04

**Screenshot of Mac Console app with release 2.5**
<img width="1132" alt="Bildschirmfoto 2021-10-26 um 17 45 44" src="https://user-images.githubusercontent.com/3425811/138914338-fbf53259-cf1a-4412-897d-7d3d07426d5b.png">

**Screenshot of Mac Console app with release 2.04**
<img width="1313" alt="Bildschirmfoto 2021-10-26 um 17 46 54" src="https://user-images.githubusercontent.com/3425811/138914620-01bdbc75-d77d-4f1e-860b-94a2cd6968c9.png">

**Comment by ArminJo** [comment]
Have you checked the [2.5 uploader](https://github.com/ArminJo/micronucleus-firmware/tree/master/commandline/builds)?
Have you checked [other bootloader variants](https://github.com/ArminJo/micronucleus-firmware/tree/master/firmware/releases)?
Else try another **Cable**, try another **USB-Port**, try another **Board**, try another **Computer**, try another **OS**.
