### ISSUE TITLE
Ext. fuse for atmega328 inconsistent in docu (and with what avrdude does)

### ISSUE THREAD

**Issue by drtrigon** [micronucleus/micronucleus#249]
The ext. fuse for atmega328 as given per docu here should be ?????101 = 0xff.

1. for me the first 5 bit have by avrdude been set to 0
2. ?101 at the end cannot give f

So for me it was set to 00000111 = 0x07. But if 101 is needed it should be 00000101 = 0x05.

**To Reproduce**
1. Look at the docu in https://github.com/micronucleus/micronucleus/blob/master/firmware/configuration/m328p_extclock/Makefile.inc#L70
2. Try to use avrdude in order to set the ext. fuse for an atmega328 to 0xff

**Expected behavior**
What is correct? Can the docu in https://github.com/micronucleus/micronucleus/blob/master/firmware/configuration/m328p_extclock/Makefile.inc#L70 be corrected?

**Used Hardware**
atmega328 and an Arduin Uno with ArduinoISP sketch

**Desktop (please complete the following information):**
 - OS: kubuntu
 - Development environment: avrdude (and Arduino IDE)
 - Version of the bootloader: current

**Comment by drtrigon** [comment]
You use `Ext: 0xFF` does  that work? What does avrdude say when trying to set the fuse like that? Doesn't it complain about the fuse walue set and recived when verifying do not agree (beeing 0x07 intead of 0xFF)?

**Comment by mihaigalos** [comment]
Yes, this worked and I was _very_ strict about the fuses in miniboot.

I haven't used avrdude but set the fuses via a mk II programmer in AVR Studio.

**Comment by drtrigon** [comment]
Nevertheless the docu here is inconsistent and should be updated.

Shall I make a pull request?

**Comment by cpldcpu** [comment]
> Shall I make a pull request?

Yes ! :)

Sorry for not being able to help further with the ATMega support, this was contributed by @AHorneffer

**Comment by ArminJo** [comment]
Sorry for being late here.
I corrected it, but please check.

**Comment by drtrigon** [comment]
Looks ok. The values are consistent and match with https://eleccelerator.com/fusecalc/fusecalc.php?chip=atmega328p

Thanks!

ps: I like the additional disabled option.
