### ISSUE TITLE
[BUG] Can't compile with ENTRYMODE ENTRY_JUMPER

### ISSUE THREAD

**Issue by archikrator** [micronucleus/micronucleus#252]
**Describe the bug**
Hello, i can't compile verison 2.6 with ENTRYMODE set to ENTRY_JUMPER. Default compilation work's fine.

**To Reproduce**
1. Edit firmware/configuration/t85_default/bootloaderconfig.h 
2. In 161 line and set `#define ENTRYMODE ENTRY_JUMPER`
3. $ make CONFIG=t85_default
4. 
```
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x2006 of main.bin section `.text' is not within region `text'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x2006 of main.bin section `.text' is not within region `text'
collect2: error: ld returned 1 exit status
make: *** [Makefile:97: main.bin] Error 1
```

**Expected behavior**
The program compiles correctly.

**Used Hardware**
Add information about the board you have been using here

**Desktop (please complete the following information):**
 - avr-libc 2.0.0
 - gcc-avr 5.4.0
 - GNU Make 4.2.1
 - Version of the bootloader: 2.6

**Comment by ArminJo** [comment]
Sorry, documentation was missing!
The error and its fix is described [there](https://github.com/micronucleus/micronucleus/tree/master/firmware#compiling-the-bootloader-firmware).
