### ISSUE TITLE
Possibly different frequency for bootloader and user code?

### ISSUE THREAD

**Issue by TheLastGimbus** [micronucleus/micronucleus#262]
I wanted to reduce power consumption of my board - one of the options is to reduce the clock speed

Sadly, looks like USB comm (and thus, this bootloader) require 12MHz at least - legit :100:

But I don't plan using usb in my Arduino code tho... would it be *ever* possible to have different clock in bootloader and user code?

**Comment by cpldcpu** [comment]
That is easily possible now. Just change the clockspeed in your user program.

**Comment by ArminJo** [comment]
Please open this topic as a discussion.
