### ISSUE TITLE
HID versus libusb

### ISSUE THREAD

**Issue by jcsistemas2001** [micronucleus/micronucleus#41]
Deae Bluebie,

Any reason to don't used a HID interface?

I cannot install a driver in the machine and I would like to use your bootloader using a HID interface. 

Can you suggest to me some advices to change the firmware/commandline to use a HID interface?

Thanks

Julio

**Comment by camerondbradley** [comment]
Hate to revive a dead thread, Julio, did you ever get micronucleus to work using HID? Would love to see the bootloader and collaborate. I think there is a great use case for HID communication without a Serial/UART Converter and driver.
