### ISSUE TITLE
Build automated test rig

### ISSUE THREAD

**Issue by Bluebie** [micronucleus/micronucleus#5]
Build a LittleWire and a digispark-type-thing and write some tool to automatically run unit tests on an attiny85, automatically resetting and talking to the µBoot software, doing firmware dumps through the ISP and making sure everything looks right, uploading simple programs and testing they work via the LittleWire and another program which talks over the USB bus to make sure the pinchange interrupts are working with V-USB.

This will make experimenting to make bootloader sizes smaller much safer.

**Comment by cpldcpu** [comment]
hmm.... avrdude does this to me.

I think I'll dare to close this issue.
