### ISSUE TITLE
Attiny167

### ISSUE THREAD

**Issue by Collie147** [micronucleus/micronucleus#64]
Tried writing 2.0b hex file to attiny167. Worked successfully but chip doesn't respond at all now.  Haven't tried high voltage reset just yet but I'm wondering could it be the fuse settings? Or perhaps that the d+ pin on the bootloaderconfig.h file is listed as portb4 which is also xtal1???

**Comment by cpldcpu** [comment]
You are right, the configuration was indeed off. I changed it to follow the Digispark Pro design. It should work now. Can you try again? You will need an external 16MHz xtal, though.

**Comment by cpldcpu** [comment]
Btw, currently the makefile does not contain any fuse setting for the ATtiny167. You need to change it manually.

**Comment by Collie147** [comment]
Thanks Tim

Unfortunately I can't write to the chips at all.  Tried it on both of
them.  I'll research into HVSP on the 167 and see if I can get it to work.
I'll let you know the updated build works ok.

Thanks again

**Comment by cpldcpu** [comment]
Well, since the micronucleus makefile does not write to the fuses of the ATtiny167, I have a hard time imagining how the firmware would be able to to render the device unresponsive? Let me know if HVSP helps.
