### ISSUE TITLE
Drivers don't install on windows 10

### ISSUE THREAD

**Issue by SoundGuy** [micronucleus/micronucleus#68]
nothing happens when i try to install the drivers on a win10 64bit.
running the installer_x64.exe  just exits and trying to install from the .inf file doesn't do anything either.

**Comment by cpldcpu** [comment]
Yes, Win10 complicates things. 

For a quick fix, you can use Zadig to install a libusb driver for the unknown device:
http://zadig.akeo.ie/

**Comment by cpldcpu** [comment]
Added Zadig option to the readme
