### ISSUE TITLE
LED_INIT macro clears DDR register

### ISSUE THREAD

**Issue by russdill** [micronucleus/micronucleus#74]
LED_INIT is called after initHardware. If one of the pins is configured as the pullup enable pin, USB_CFG_PULLUP_BIT, then initHardware will call usbDeviceConnect which will set that pin as an output. LED_INIT then clears all the bits in the DDR register, disabling the pullup.

This is true of all the LED_INIT macros in all the bootloaderconfig.h headers. The LED_INIT macro just needs to be changed to a bit set (|=) instead of a simple assign.

**Comment by cpldcpu** [comment]
Indeed, a "|" was missing there. Thanks for letting me know!

Fixed!
