### ISSUE TITLE
Not compiling in fedora 23 x64

### ISSUE THREAD

**Issue by rm3nchaca** [micronucleus/micronucleus#81]
It gives a lot of errors because of usb.h:

Executing make in Fedora 23 x64 gives a lot of errors like this:

In file included from library/micronucleus_lib.c:30:0:
library/micronucleus_lib.h:68:3: error: unknown type name ‘libusb_device_handle’
   libusb_device_handle *device;
.
.
.
.

I 've compiled it with a little workaround in micronucleus_lib.h:
```
#if defined WIN
  #include <libusb.h>     // this is libusb, see http://libusb.sourceforge.net/
#else
  //include <usb.h>        // this is libusb, see http://libusb.sourceforge.net/
  #include <libusb-1.0/libusb.h>
```
And also in the Makefile:

```
#CFLAGS  = $(USBFLAGS) $(LIBS) -I$(INCLUDE) -O -g $(OSFLAG)
CFLAGS  = -lusb-1.0 $(LIBS) -I$(INCLUDE) -O -g $(OSFLAG)
```

I have no experience with make neither compiling, maybe just adding an additional condition depending of the linux distro solve the problem.

In the meantime, you can use this if you are getting trouble compiling in fedora.

Greetings!

**Comment by cpldcpu** [comment]
This seems to be a version conflict of libusb, not specifically limited to fedora.

**Comment by rm3nchaca** [comment]
You're right, the definitions in the .h file are different and in Fedora
you need to specify de version of libusb.

**Comment by Schm1tz1** [comment]
Does this problem still persist ? I have just been compiling the recent version on FC23 x64 without any problems. Maybe a version conflict ?

**Comment by cpldcpu** [comment]
As mentioned, this rather seems to be related to the libusb version that's installed. I'll close this issue to avoid confusion.
