### ISSUE TITLE
user program gets corrupted occasionally

### ISSUE THREAD

**Issue by Genoil** [micronucleus/micronucleus#92]
I have a custom PCB with (among other parts):
- attiny84A
- 12 Mhz crystal
- fuses: low:0xff high: 0xdf ext:0xfe. 
- button (active high)
- LED (active high, driven from MCU)
- no RESET circuit/button
- on/off switch
- ISP header
- micro-USB port

I have a custom micronucleus configuration for this, based on the t84_default config. The main differences are pin assignments, and a change to the stock ENTRY_JUMPER code that allows using my button as a JUMPER to conditionally enter the bootloader when the button is held down while switching the device on:

```
#elif ENTRYMODE==ENTRY_JUMPER2
  #define bootLoaderInit()   {JUMPER_DDR&=~_BV(JUMPER_PIN);JUMPER_PORT&=~_BV(JUMPER_PIN);_delay_ms(1);}
  #define bootLoaderExit()   {JUMPER_PORT|=_BV(JUMPER_PIN);}
  #define bootLoaderStartCondition() ((JUMPER_INP&_BV(JUMPER_PIN)))
```

This works great! I can upload application firmware via USB and don't have to wait x seconds of bootloading timeout when he device is switched on by my end user. 

Now, the problem. I have 6 prototypes programmed and tested like this and now yesterday and today 2 of the boards (one of them twice) have gotten into a state where when you switch them on, the user application won't start, but entering the bootloader still works.

== major update after this line ==

I am now able to more or less force a board into this state by switching the the device on and off very quickly while randomly holding the button down or not. I have compared the flash contents of both working and several corrupted instances and noticed that on each corrupted instance, there are one or more (2 or 3 at most) 64 byte (SPM_PAGESIZE) blocks of flash erased to 0xff, at random locations in the file. Why the bootloader is able to get into this state is still a mystery. Perhaps there is a bug in the user program that makes it jump to boot_page_erase?

**Comment by cpldcpu** [comment]
This is the first time I hear of this issue. In principle, it is of course possible for a user program to corrupt itself. There is no write protection in the ATTiny, so it is impossible to prevent this.

**Comment by AHorneffer** [comment]
Jaja, I'm late to the party... but I might still have some useful information. 

If I see that correctly, then you have the brown-out detection in the ATtiny disabled. I had a similar problem on an ATmega328p, sometimes so flash-pages got erased. After I got a tip on another forum and switched on the brown-out detection, this problem vanished. 

It is unsurprising that micro-controllers behave erratically when the voltage is too low, and it is apparently not too uncommon that they erase part of their flash when that happens.
