### ISSUE TITLE
328p????

### ISSUE THREAD

**Issue by dunk8888** [micronucleus/micronucleus#99]
Hi strange question i know but could i use this on 328p with some miner changes or would it be difficult for a begginer to do?i just like how arduino waits till digispark is plugged in then uploads,usbasploader is pretty mutch the same but you have to plug in the 328p and hope it doesnt time out befor code is uploaded, sometimes my ide takes ages to compile the code and misses the bootloader this is why i ask about using this instead for the 328p. or is ther a way to make usbasploader o the same thing and wait till the board is pluged in? they are both based on v-usb thanks

**Comment by cpldcpu** [comment]
See https://github.com/micronucleus/micronucleus/issues/107

closing.
